const INSTALL_SH = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "",
  "log() {",
  "  printf \"[lexis-install] %s\\n\" \"$*\"",
  "}",
  "",
  "fail() {",
  "  printf \"[lexis-install] error: %s\\n\" \"$*\" >&2",
  "  exit 1",
  "}",
  "",
  "has_cmd() {",
  "  command -v \"$1\" >/dev/null 2>&1",
  "}",
  "",
  "require_cmd() {",
  "  if ! has_cmd \"$1\"; then",
  "    fail \"missing required command: $1\"",
  "  fi",
  "}",
  "",
  "append_user_path_exports() {",
  "  local line='export PATH=\"$HOME/.local/bin:$PATH\"'",
  "  local rc",
  "",
  "  for rc in \"$HOME/.profile\" \"$HOME/.bashrc\" \"$HOME/.zshrc\"; do",
  "    if [ ! -f \"$rc\" ]; then",
  "      touch \"$rc\"",
  "    fi",
  "",
  "    if ! grep -Fq \"$line\" \"$rc\"; then",
  "      printf \"\\n%s\\n\" \"$line\" >> \"$rc\"",
  "    fi",
  "  done",
  "}",
  "",
  "install_global_with_fallbacks() {",
  "  local source=\"$1\"",
  "",
  "  if npm install -g \"$source\"; then",
  "    return 0",
  "  fi",
  "",
  "  if [ \"$(id -u)\" -ne 0 ] && has_cmd sudo; then",
  "    log \"Global install needs elevated permissions. Retrying with sudo...\"",
  "    if sudo npm install -g \"$source\"; then",
  "      return 0",
  "    fi",
  "  fi",
  "",
  "  local user_prefix=\"$HOME/.local\"",
  "  log \"Falling back to user-level npm prefix: $user_prefix\"",
  "  npm install -g --prefix \"$user_prefix\" \"$source\"",
  "  export PATH=\"$user_prefix/bin:$PATH\"",
  "  append_user_path_exports",
  "  return 0",
  "}",
  "",
  "require_cmd node",
  "require_cmd npm",
  "",
  "SOURCE=\"${LEXIS_INSTALL_SOURCE:-@hridyacodes/lexis}\"",
  "log \"Installing Lexis from: $SOURCE\"",
  "install_global_with_fallbacks \"$SOURCE\"",
  "",
  "if ! has_cmd lexis; then",
  "  fail \"'lexis' command not found after install\"",
  "fi",
  "",
  "HOOK_MODE=\"${LEXIS_HOOK_MODE:-}\"",
  "PROFILE=\"${LEXIS_PROFILE:-}\"",
  "",
  "ARGS=(setup --enable-web-search --web-provider mcp)",
  "if [ -n \"$PROFILE\" ]; then",
  "  ARGS+=(--profile \"$PROFILE\")",
  "fi",
  "if [ -n \"$HOOK_MODE\" ]; then",
  "  ARGS+=(--hook-mode \"$HOOK_MODE\")",
  "fi",
  "",
  "log \"Running setup\"",
  "lexis \"${ARGS[@]}\"",
  "",
  "log \"Done. Open a new terminal and run: lx doctor\"",
].join("\n") + "\n";

export function GET() {
  return new Response(INSTALL_SH, {
    status: 200,
    headers: {
      "content-type": "text/x-shellscript; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
