const INSTALL_SH = [
  "#!/usr/bin/env bash",
  "set -euo pipefail",
  "",
  "log() {",
  "  printf \"[lexis-install] %s\\n\" \"$*\"",
  "}",
  "",
  "fail() {",
  "  printf \"[lexis-install] error: %s\\n\" \"$*\" >&2",
  "  exit 1",
  "}",
  "",
  "has_cmd() {",
  "  command -v \"$1\" >/dev/null 2>&1",
  "}",
  "",
  "require_cmd() {",
  "  if ! has_cmd \"$1\"; then",
  "    fail \"missing required command: $1\"",
  "  fi",
  "}",
  "",
  "require_cmd node",
  "require_cmd npm",
  "",
  "SOURCE=\"${LEXIS_INSTALL_SOURCE:-@hridyacodes/lexis}\"",
  "log \"Installing Lexis from: $SOURCE\"",
  "npm install -g \"$SOURCE\"",
  "",
  "if ! has_cmd lexis; then",
  "  fail \"'lexis' command not found after install\"",
  "fi",
  "",
  "HOOK_MODE=\"${LEXIS_HOOK_MODE:-}\"",
  "PROFILE=\"${LEXIS_PROFILE:-}\"",
  "",
  "ARGS=(setup --enable-web-search --web-provider mcp)",
  "if [ -n \"$PROFILE\" ]; then",
  "  ARGS+=(--profile \"$PROFILE\")",
  "fi",
  "if [ -n \"$HOOK_MODE\" ]; then",
  "  ARGS+=(--hook-mode \"$HOOK_MODE\")",
  "fi",
  "",
  "log \"Running setup\"",
  "lexis \"${ARGS[@]}\"",
  "",
  "log \"Done. Open a new terminal and run: lx doctor\"",
].join("\n") + "\n";

export function GET() {
  return new Response(INSTALL_SH, {
    status: 200,
    headers: {
      "content-type": "text/x-shellscript; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
