const INSTALL_PS1 = [
  "param()",
  "$ErrorActionPreference = \"Stop\"",
  "",
  "function Require-Command([string]$Name) {",
  "  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {",
  "    throw \"Missing required command: $Name\"",
  "  }",
  "}",
  "",
  "function Add-CommonNodePaths {",
  "  $candidates = @(",
  "    (Join-Path $env:ProgramFiles \"nodejs\"),",
  "    (Join-Path ${env:ProgramFiles(x86)} \"nodejs\"),",
  "    (Join-Path $env:LOCALAPPDATA \"Programs\\nodejs\")",
  "  )",
  "",
  "  foreach ($path in $candidates) {",
  "    if ($path -and (Test-Path $path) -and -not ($env:Path.Split(';') -contains $path)) {",
  "      $env:Path = \"$path;$env:Path\"",
  "    }",
  "  }",
  "}",
  "",
  "function Ensure-Npm {",
  "  if (Get-Command npm -ErrorAction SilentlyContinue) {",
  "    return",
  "  }",
  "",
  "  Write-Host \"[lexis-install] npm not found. Attempting to install Node.js LTS...\"",
  "",
  "  if (Get-Command winget -ErrorAction SilentlyContinue) {",
  "    winget install --id OpenJS.NodeJS.LTS -e --accept-source-agreements --accept-package-agreements --silent | Out-Host",
  "  }",
  "  elseif (Get-Command choco -ErrorAction SilentlyContinue) {",
  "    choco install nodejs-lts -y | Out-Host",
  "  }",
  "  elseif (Get-Command scoop -ErrorAction SilentlyContinue) {",
  "    scoop install nodejs-lts | Out-Host",
  "  }",
  "  else {",
  "    throw \"npm is missing and no package manager was found. Install Node.js LTS, then rerun installer.\"",
  "  }",
  "",
  "  Add-CommonNodePaths",
  "",
  "  if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {",
  "    throw \"npm is still unavailable after auto-install attempt\"",
  "  }",
  "}",
  "",
  "Ensure-Npm",
  "Require-Command node",
  "Require-Command npm",
  "",
  "$source = if ($env:LEXIS_INSTALL_SOURCE) { $env:LEXIS_INSTALL_SOURCE } else { \"@hridyacodes/lexis\" }",
  "Write-Host \"[lexis-install] Installing Lexis from: $source\"",
  "npm install -g $source | Out-Host",
  "",
  "if (-not (Get-Command lexis -ErrorAction SilentlyContinue)) {",
  "  throw \"'lexis' command not found after install\"",
  "}",
  "",
  "$args = @('setup', '--enable-web-search', '--web-provider', 'mcp')",
  "if ($env:LEXIS_PROFILE) {",
  "  $args += @('--profile', $env:LEXIS_PROFILE)",
  "}",
  "if ($env:LEXIS_HOOK_MODE) {",
  "  $args += @('--hook-mode', $env:LEXIS_HOOK_MODE)",
  "}",
  "",
  "Write-Host \"[lexis-install] Running setup\"",
  "lexis @args | Out-Host",
  "Write-Host \"[lexis-install] Done. Open a new terminal and run: lx doctor\"",
].join("\n") + "\n";

export function GET() {
  return new Response(INSTALL_PS1, {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}
